/*
 * precompiled.h
 *
 *  Created on: 29.02.2020
 *      Author: doene
 */

#ifndef REPS_HERP_FRONTENDPROVIDER_HERP_FRONTENDPROVIDER_PRECOMPILED_H_
#define REPS_HERP_FRONTENDPROVIDER_HERP_FRONTENDPROVIDER_PRECOMPILED_H_

#include <HERP.FrontendProvider.Export.h>
#include <QxOrm.h>


#endif /* REPS_HERP_FRONTENDPROVIDER_HERP_FRONTENDPROVIDER_PRECOMPILED_H_ */
